# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pathlib
        pip install jinja2
    - name: Delete old file
      run: |
        git config user.email "lukeormiston@gmail.com"
        git config user.name "GH Action"
        git checkout main/pages
        git pull origin main
        ls -la
        rm www/index.html
        git add .
        git commit -m "Removed old index.html"
    - name: Generate HTML file
      run: |
        python generate.py
    - name: Push generated HTML
      run: |
        git add www/index.html
        git commit -m "Generated index.html"
        git push
